version: '3.8'
services:
  web:
    container_name: sports_city
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=${NODE_ENV}
    command: npm run dev